name: Waka Readme

on:
  workflow_dispatch:
  schedule:
     # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: ░▒▓█ # optional
          CODE_LANG: javascript # optional
          TIME_RANGE: last_30_days # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML TOML # optional
          ### commit
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          AUTHOR_NAME: oulehlajan # optional
          AUTHOR_EMAIL: oulehlajan@gmail.com # optional
